apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
  namespace: default
  annotations:
      # 1. Native safe way to rewrite session cookies over plain HTTP
    nginx.ingress.kubernetes.io/session-cookie-conditional-samesite: "None"
    # 2. Native safe way to fix the 302 location redirects
    nginx.ingress.kubernetes.io/proxy-redirect-from: "off"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-redirect-default: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://localhost:8080/"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-svc       # Your ClusterIP service name
            port:
              number: 80           # The port your service exposes
